### PR TITLE
Start on 2.7

### PR DESCRIPTION
**Pull request by robertylewis**

### CODE REVIEW

**Comment by avigad** [comment]
Thanks! In answer to your question, when talking about natural deduction, we'll use $\top$ and $\bot$, and in Lean, of course, we'll use `true` and `false`.

@rlewis1988 I think the link associated with my name on the title page of the PDF version comes from the metadata at the top of 01_Introduction.org. I will add links to your and Floris' web pages as well.

**Comment by robertylewis** [comment]
My question was about notation for the truth values themselves. For a valuation, we want to say something like v('P') = T. I didn't feel good about using top/bottom there, since like you say they're also used in natural deductions. Boldface T/F would be better, maybe (but I wasn't sure how to make new commands for those). Or we could use 1 and 0, but that might not be appropriate at this level... I'm not sure.

**Comment by robertylewis** [comment]
Oops, and the commit to header/latex.tex was really meant to change line 162. I think I didn't save that change.

**Comment by avigad** [comment]
Ah, I see. For writing out truth tables, maybe it is best to use T / F. We'll students to turn in one or two of them for homework, and writing T and F will be more familiar.

**Pull request merged**
