### PR TITLE
List and equation punctuation

### PR DESCRIPTION
**Pull request by robertylewis**
This is an attempt to make consistent the punctuation and capitalization of lists and displayed equations. I have only finished through chapter 18.

Basically, I'm trying to follow these guidelines, which are roughly what was followed in the early chapters.

- The presence of a list or an equation ends a sentence, with a few exceptions for the latter, whether or not it is preceded by a colon. I may have been a bit too aggressive implementing this around chapters 13-15 -- it became hard to keep up later on.
- Lists of complete sentences are capitalized and punctuated. Lists of incomplete sentences are lowercase and unpunctuated.
- Equations are always unpunctuated.

These conventions seemed internally consistent and the least disruptive to implement. I don't doubt that I've violated them a few times here, though.

- The voice in my head disagrees with your reverting introduction.rst:236. I concede the trailing period. But while the points are, indeed, not full sentences, they are separate emphasized thoughts. I read them with the beginning emphasized, which to me calls for a capital letter. There is some disagreement on StackOverflow: https://english.stackexchange.com/questions/55048/use-of-capitals-and-full-stops-in-bullet-points https://english.stackexchange.com/questions/9752/capitalization-for-a-bullet-list, but nothing official. The Wikipedia style guide apparently suggests capitalizing and ending with semicolons, which I don't like. https://english.stackexchange.com/questions/5241/periods-for-bullet-point-items

However! Reading the sentences again, they don't adhere to "best practice" for educational material. Course objectives are supposed to be phrased in terms of goals for students, not goals for the course/lecturer. (Source: Eberly Center materials that I don't have in front of me right now.) We can solve to problems at once by rephrasing to student-oriented complete sentences.

(Yes, this is probably two paragraphs too many on this subject.)

- I don't like propositional_logic.rst:630 and the two lists that immediately follow. In the first, the bullets are acting as commas (or semicolons) and are part of the preceding sentence, and the preceding colon is internal to the sentence. In the second and third, the preceding colon is ending the sentence and introducing the list, in which each item is a separate fragment. These are both correct usages (as I understand it), but the first reads oddly to me, and the different usages right next to each other hurts my eye a little. My ideal solution is to rewrite the first to no longer be a bullet-point list. Do you agree?

- relations.rst was internally inconsistent. I decided the best fix was to remove all trailing periods for "axiom lines," since that most closely parallels earlier chapters. But these lines can be read as complete sentences, in which case each should be capitalized and punctuated. 

- Not unrelated is the punctuation of equations. Early in the text, we often end sentences with a colon, followed by an unpunctuated displayed equation. Toward the middle, we do similarly, but without the colon, where the equation serves as the last grammatical expression of the sentence (still unpunctuated, following word capitalized). functions.rst (and later) punctuates its equations mid-sentence and at the end. I'm comfortable with the first two existing in parallel. Do you agree?

### CODE REVIEW

**Comment by avigad** [comment]
I just checked about twenty math books on my shelves, and _every single one of them_ handles punctuation in a displayed equation in the same way, namely, as though it were an integral part of the text. In other words, if the displayed equation ends a sentence, there is a period at the end. If a comma would appear if it were in the main text, there is a comma at the end. None of the books hesitates to make a displayed equation an integral part of the sentence, without punctuation.

I have a strong preference to follow these conventions. We should be writing mathematics the way it is conventionally written in ordinary math texts, and, as far as I can tell, the style is remarkable uniform.

I agree with the conventions regarding list items: capitalization and period for full sentences, other items lowercase and unpunctuated. Turning the goals into sentences is a good idea.

For the order of operations in propositional logic, I would prefer to keep a list format. We can follow the same strategy of turning them into sentences. From a pedagogical point of view, I think that making the order of the steps prominent by displaying as a list makes them easier to process and remember.

The upshot is that I propose to adopt all the commits except for the second one and the second and third from last, and fix the order of operations list and the fix the induction chapter also. (By our conventions, it seems that the items in the exercises need to be capitalized, and need periods at the end.)

@rlewis1988 Is that o.k. with you? I think I can perform the necessary git-fu with `git rebase -i`.

**Comment by avigad** [comment]
P.S. Whether or not there is a colon before a displayed equation should be determined by whether or not there would be a colon if the expression were to appear in an ordinary sentence.

**Comment by robertylewis** [comment]
Honestly, the reason this stuck out to me was because someone (a reviewer or a reader, I don't remember) complained about my equation formatting in my Mathematica paper. I had it as you describe, always punctuated and as an integral part of the sentence, and was told that this went against CS paper customs. (Note, I didn't change it.) I don't have time to check a sample size of 20, but here are a few. These are the only ones I looked at that had a consistent pattern; more than half had a mix of styles.
- http://matryoshka.gforge.inria.fr/pubs/sat_2wl_paper.pdf p.7 left column: commas included in equations, periods omitted
- https://link.springer.com/content/pdf/10.1007%2Fs10817-017-9424-6.pdf all punctuation included
- http://www.cs.cmu.edu/~aplatzer/pub/acasx-zones-long.pdf equations only introduced with colons, always ending the sentence, unpunctuated
- http://www.cl.cam.ac.uk/~jrh13/papers/wz.pdf all equations unpunctuated, whether or not they end the sentence, whether or not they are introduced with a colon

Given this, I'm surprised the textbooks on your shelf are so consistent! I don't have any handy right now to check myself.

I don't particularly care what convention we follow, as long as we're internally consistent, which we weren't before. Are you proposing 100% punctuated, even when introduced by a colon? Punctuated, except when introduced by a colon? Presumably Lean code blocks will be handled differently?

**Comment by robertylewis** [comment]
> P.S. Whether or not there is a colon before a displayed equation should be determined by whether or not there would be a colon if the expression were to appear in an ordinary sentence.

Yes, but we favor one style at the beginning of the book, and another in the middle. I guess it's probably unnoticeable unless you're scanning the text for equation formatting, like I was, but there is a shift.

**Comment by robertylewis** [comment]
> The upshot is that I propose to adopt all the commits except for the second one and the second and third from last

In the order they're displayed right above your post? I think the second commit should be kept, or otherwise, all items in that list should be unpunctuated. Having two unpunctuated and three punctuated items in one list looks awful, and you can read each item as a complete sentence, even the equations.

**Comment by avigad** [comment]
There's probably more variation in CS conference papers, which are typeset by the authors and not reviewed by professional typesetters. Also code snippets and tables of proof rules are treated differently. But I just checked three CS books on my shelf, and they too are uniform in the way I described when it comes to mathematical expressions. So, yes, I propose putting punctuation in displayed equations after colons, as though the equations are part of a regular sentence. I didn't follow that practice before, but it is uniformly done in every example I have looked at.

Regarding your last comment, I made a mistake. I meant to exclude the *first* commit, "annoying non-parallel bullet constructions". Let's keep the list, but make the bullets full sentences.

I can do this over the weekend, unless you would prefer to.

**Comment by robertylewis** [comment]
I found the quote about my Mathematica paper, from Jasmin, unsurprisingly ;)

> Throughout: Mathematicians tend to punctuate displayed material, but computer scientists have largely given up. (I gave up in 2010, after a reviewer dismissed my sophisticated punctuation scheme as "inconsistent".) 

So that helps explain it. Regardless, your proposal is fine with me! We should be sure to check chapters 19+, which these commits don't address.

I won't have time until Sunday evening at the earliest. So if you want to make the changes before then, great, otherwise I can give it a shot then.

**Comment by robertylewis** [comment]
Replaced by #14

**Pull request closed without merging**
